### ISSUE TITLE
分類マスタインポートエラー

### ISSUE THREAD

**Issue by AriPSS** [miyabiit/kenki-catalogdb#37]
@centrevillage 

ステージングで、
企業コード：CH-001
ユーザーID：staffc001
で、添付の分類マスタを選択して、インポートボタンを押下したところ、添付のエラーが発生しました。
確認お願いします。

[categories_2020090401.zip](https://github.com/miyabiit/kenki-catalogdb/files/5172752/categories_2020090401.zip)

![error_2020090401](https://user-images.githubusercontent.com/12669075/92201083-815c7480-eeb6-11ea-843c-f069f5988cc1.JPG)

**Comment by centrevillage** [comment]
カテゴリ名の一意制約エラーが発生しています:

```
F, [2020-09-04T05:51:46.251838 #27293] FATAL -- : [6cf9341c-6275-4158-8e1f-3ed1ad82a93a]
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a] ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '2-マグネット式LEDライト' for key 'index_categories_on_company_id_and_name'):
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a]
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a] app/imports/category_import.rb:34:in `block in process_csv'
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a] app/imports/category_import.rb:25:in `each'
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a] app/imports/category_import.rb:25:in `process_csv'
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a] app/imports/import_base.rb:12:in `block in import'
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a] app/imports/import_base.rb:10:in `import'
[6cf9341c-6275-4158-8e1f-3ed1ad82a93a] app/controllers/categories_controller.rb:75:in `upload'
```

CSVデータをみると `マグネット式LEDライト` カテゴリに親カテゴリが複数存在するため、キーが重複してしまうようです。

DBテーブルの構造上、複数の親を持つカテゴリは作れないので、子のカテゴリ名（この場合 `マグネット式LEDライト` ) をリネームしていただくか、特定の親のみに属するようにする必要があります。

**Comment by AriPSS** [comment]
@centrevillage 
データかと思いましたが、確認が取れてなくてすみません。了解です。

**Comment by AriPSS** [comment]
@centrevillage 
該当のカテゴリ=マグネット式LEDライトのレコードを削除して登録したのですが、エラーになりました。
（エラー画面は先程と同じです）
確認をお願いします。

[categories_2020090402.zip](https://github.com/miyabiit/kenki-catalogdb/files/5173884/categories_2020090402.zip)

**Comment by centrevillage** [comment]
まだ重複したカテゴリーが複数残っているようです。

[categories_2020090402.xlsx](https://github.com/miyabiit/kenki-catalogdb/files/5174095/categories_2020090402.xlsx)
(excel で重複チェックしてみました）

**Comment by AriPSS** [comment]
@centrevillage 有難うございます。取り込めました。
